config/routes.rb
Rails.application.routes.draw do
  root 'market#homepage'
  devise_for :users

  get 'cards/:id', to: 'cards#show', as: "card"
  

  get 'market/homepage', to: 'market#homepage'
  get 'market/card/new', to: 'market#new'
  post 'market/card', to: 'market#create'
  get 'market/show/:id', to:'market#show', as:'market_show'

  get 'market/sell_card', to: 'market#sell_card'
  
  get 'market/about', to: 'market#about'

  get 'market/sold', to: 'market#sold'

  get 'market/contact', to: 'market#contact'

  get 'listings/index', to: 'listings#index'

  get '/payments/success', to: 'payments#success'

  get 'listings/new', to: 'listings#new'

  post 'listings/new', to: 'listings#create'

  resources :cards

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :listing, required: false
    has_many :clans
    has_many :conditions
    has_many :orders
    has_one_attached :picture
end

app/models/clan.rb
class Clan < ApplicationRecord
    belongs_to :card, required: false
end

app/models/condition.rb
class Condition < ApplicationRecord
    belongs_to :card, required: false
end

app/models/listing.rb
class Listing < ApplicationRecord
    validates :price, numericality: { :less_than_or_equal_to => 999 }
    belongs_to :user, required: false
    has_many :cards, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user, required: false
    belongs_to :card, required: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :listings
         has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def index
        @cards = Card.all
    end
    
    def edit
        @card = Card.find(params[:id])
        unless current_user == @card.listing.user
            redirect_to listings_index_path, notice: "You cannot edit this listing" and return
        
    end

    end

    def update
        card_params = params.require(:card).permit(:name, :image_url, :clan_id, :condition_id, :listing_id, :picture )
        @card = Card.find(params[:id])
        @card.update(card_params)
        redirect_to listings_index_path
    end

    def destroy
        @card = Card.find(params[:id])
        @card.destroy
        redirect_to listings_index_path
    end
    
    def show
    end

    private

    def card_params
        card_params = params.require(:card).permit(:name, :image_url, :clan_id, :condition_id, :listing_id, :picture )
    end 

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    def index
        @cards = Card.where("sold = false")
    end

    def list
        @listing = Listing.new
    end
    
    def new
        @listing = Listing.new
    end

    def create
        @listing = Listing.new(listing_params)
        @listing.user_id = current_user.id
        @listing.save
        redirect_to market_card_new_path
    end
    
    def edit
        @card = Card.find(params[:id])
        unless current_user == @card.listing.user
            redirect_to listings_index_path, notice: "You cannot edit this listing" and return
        end
    end

    def update
        card_params = params.require(:card).permit(:name, :image_url, :clan_id, :condition_id, :listing_id, :picture )
        @card = Card.find(params[:id])
        @card.update(card_params)
        redirect_to listings_index_path
    end

    def destroy
        @card = Card.find(params[:id])
        @card.destroy
        redirect_to listings_index_path
    end
    
    def show

        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.email,
            line_items: [{
                name: @listing.title,
                description: @listing.description,
                amount: @listing.price * 100,
                currency: 'aud',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    user_id: current_user.id,
                    listing_id: @listing.id
                }
            },
            success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@listing.id}",
            cancel_url: "#{root_url}listings"
        )
    
        @session_id = session.id
    end

    private

    def card_params
        card_params = params.require(:card).permit(:name, :image_url, :clan_id, :condition_id, :listing_id, :picture, :sold )
    end 
    def listing_params
        listing_params = params.require(:listing).permit(:title, :price, :user_id )
    end

end

app/controllers/market_controller.rb
class MarketController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :sell_card]
  def homepage
  end

  def about
  end
  
  def sell_card
    @card.sold = true
    respond_to do |format|
      if @card.save
        format.html { redirect_to market_sold_path, notice: 'card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def sold 
    @cards = Card.where("sold = true")
  end

  def contact
  end

  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      line_items: [{
          name: @card.listing.title,
          amount: (@card.listing.price * 100).to_i,
          currency: 'aud',
          quantity: 1,
      }],
      payment_intent_data: {
          metadata: {
              user_id: current_user.id,
              listing_id: @card.listing.id
          }
      },
      success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@card.listing.id}",
      cancel_url: "#{root_url}listings"
    )

    @session_id = session.id
  end

  def new
    @card = Card.new
  end

  def edit
    @card = Card.find(params[:id])
  end

  # POST /card
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.save
    redirect_to listings_index_path(@card)
  end
    
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(card_params)
        format.html { redirect_to @card, notice: 'card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end
  

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:name, :image_url, :condition_id, :clan_id, :listing_id,:picture, :sold)
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def success
        @listing = Listing.find(params[:listingId])
        @listing.cards.update_all(sold: true)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/market_helper.rb
module MarketHelper
end

app/views/cards/_form.html.erb
<%= form_with model:card do |form| %>
  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :clan_id %>
    <%= form.select :clan_id, options_for_select( Clan.all.collect { |u| [u.name, u.id] } ), :selected => @card.clan_id %>
  </div>

  <div class="field">
    <%= form.label :condition_id %>
    <%= form.select :condition_id, Condition.all.collect{|u| [u.card_type, u.id]} %>
  </div>

  <div class="field">
    <%= form.label :listing_id %>
    <%= form.select :listing_id, Listing.all.collect { |u| [u.title, u.id] } %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h>Edit</h1>

<td><%= render 'form', card: @card %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>Vanguard Marketplace</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">


            <% if user_signed_in? %>
              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.email, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>
            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>
            

            <% end %>
            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model:listing, url:listings_new_path) do |form| %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
 
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
   </div>
   <% end %>

app/views/listings/_navbar.html.erb
<nav class="navbar">
    <ul>
        <li><%= link_to 'Home', market_homepage_path, class:"navlink" %></li>
        <li><%= link_to 'Make a Listing', listings_index_path, class:"navlink" %></li>
        <li><%= link_to 'Sold Listings', market_sold_path, class:"navlink" %></li>
        <li><%= link_to 'About Us', market_about_path, class:"navlink" %></li>
        <li><%= link_to 'Contact Us', market_contact_path,class:"navlink" %></li>
    </ul>
</nav>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'navbar'%>

<h1>Card Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Clan</th>
      <th>Condition</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= Clan.find(card.clan_id).name %></td>
        <td><%= Condition.find(card.condition_id).card_type %></td>
        <td><%= Listing.find(card.listing_id).user.email %></td>
        <td><%= link_to 'Show', market_show_path(card), class:"show" %></td> 
        <% if card.listing.user_id == current_user.id  %>
          <td><%= link_to 'Edit', edit_card_path(card), class:"show" %></td>
          <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' }, class:"show" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Card Listing', listings_new_path %></button>

app/views/listings/new.html.erb
<%= render 'navbar'%>

<h1>Listing Information</h1>

<%= render 'form', listing: @listing %>

<% link_to 'Back' %>

app/views/market/_form.html.erb
<%= form_with(model:@card, url:market_card_path) do |form| %>
  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :clan_id %>
    <%= form.select :clan_id, options_for_select( Clan.all.collect { |u| [u.name, u.id] } ), :selected => card.clan_id %>
  </div>

  <div class="field">
    <%= form.label :condition_id %>
    <%= form.select :condition_id, Condition.all.collect{|u| [u.card_type, u.id]} %>
  </div>

  <div class="field">
    <%= form.label :listing_id %>
    <%= form.select :listing_id, Listing.where(user_id: current_user.id).collect { |u| [u.title, u.id] } %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<button><%= link_to 'Back', listings_index_path %></button>

app/views/market/_navbar.html.erb
<nav class="navbar">
    <ul>
        <li><%= link_to 'Home', market_homepage_path, class:"navlink" %></li>
        <li><%= link_to 'Make a Listing', listings_index_path, class:"navlink" %></li>
        <li><%= link_to 'Sold Listings', market_sold_path, class:"navlink" %></li>
        <li><%= link_to 'About Us', market_about_path, class:"navlink" %></li>
        <li><%= link_to 'Contact Us', market_contact_path,class:"navlink" %></li>
    </ul>
</nav>

app/views/market/about.html.erb
<%= render 'navbar'%>

<h1>This is the About Us page</h1>

<h2>Who Are We</h2>

<p> We are your most reliable seller of trading cards, specialising in Cardfight Vanguard. Found in 2019 by Jason Liu, the owner of this online marketplace.</p>

<h2>Our History</h2>

<p>Being a huge fan of the cardfight vanguard game, one day Jason was planning out a business. He originally came up with a few ideas, but the one that fascinated him most was the thought of having a online card trading marketplace. Originally the plan was to create an online card store specialising in many different trading card games, however after further thought, we decided to instead focus on CardFight Vanguard as our main trading card game market. We are a fairly new business to the online marketplace, so if things ever go wrong, feel free to contact us at anytime. Furthermore you can contact the owner himself using his email.</p>
</div>

app/views/market/contact.html.erb
<%= render 'navbar'%>

<div class="contact-contentcontainer">
            <div class="contact-title">
                <h1 id="contacttext">Contact</h1>
                <h2 id="contacttext">Got enquiries? Feel free to contact us anytime!</h2>
            </div>
<div class="contact-form">
                <form action="https://formspree.io/email@domain.tld" method="POST" />
                <form id="contact-form" method="post" action="">
                    <input name="name" type="text" class="form-control" placeholder ="Your Name" required><br>
                    <input name="email" type="email" class="form-control" placeholder ="Your Email" required><br>
                    <textarea name="message" class="form-control" placeholder="Message" required></textarea><br>
                    <input type ="Submit" class="form-control submit" value="Send Message">
                </form>
</div>            

app/views/market/edit.html.erb
<%= render 'navbar'%>

<h1>Editing a Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %>

<%= link_to 'Back', cards_path %>

app/views/market/homepage.html.erb
<%= render 'navbar'%>

<h1>Vanguard Marketplace</h1>

<p>Find all your vanguard singles that you need here!</p>

app/views/market/new.html.erb
<%= render 'navbar'%>

<h1>New Card Listing</h1>

<%= render 'form', card: @card %>

<% link_to 'Back', cards_path %>

app/views/market/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'navbar'%>

<h1> Card Listing</h1>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Clan:</strong>
  <%= Clan.find(@card.clan_id).name %>
</p>

<p>
  <strong>Card condition:</strong>
  <%= Condition.find(@card.condition_id).card_type %>
</p>

<p>
  <strong>Listing title:</strong>
  <%= Listing.find(@card.listing_id).title %>
</p>

<p>
  <%= image_tag(@card.picture,size:'200x300') if @card.picture.attached? %>
</p>

<p>
  <strong>Price:</strong>
  <%= Listing.find(@card.listing_id).price %>
</p>
<% if @card.listing.user == current_user  %>
<%= link_to 'Edit', edit_card_path(@card) %> 
<% end %>
<% if @card.listing.user != current_user %>
<button data-stripe="payment" >Buy Now <%= number_to_currency(@card.listing.price) %></button>
<% end %>
<%= link_to 'Back', listings_index_path %>



<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>

app/views/market/sold.html.erb
<p id="notice"><%= notice %></p>

<%= render 'navbar'%>

<h1>Sold Card Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Clan</th>
      <th>Condition</th>
      <th>Sold by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
        <% if card.sold == true %>
            <tr>
                <td><%= card.name %></td>
                <td><%= Clan.find(card.clan_id).name %></td>
                <td><%= Condition.find(card.condition_id).card_type %></td>
                <td><%= Listing.find(card.listing_id).user.email %></td>
                <% if card.listing.user == current_user  %>
                    <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/market/unused_assets.html.erb
<!-- <h1>This is the listing page </h1>
 ? card.clan_id.name : ""
 <td><%= image_tag( card.image_url , size: "200x300") %></td>
<% @cards.each do |card| %>
<h3>Name: <%= card.name  %></h3>
    <h3>Image: <%= image_tag(card.image_url,size:'200x300') %></h3>
    <h3>Clan: <%= Clan.find(card.clan_id).name if card.clan_id != nil  %></h3>
    
<% end %>  -->

app/views/payments/success.html.erb
You've successfully made a payment! <%= link_to "Go To Listings", listings_index_path
%>